#TO JEST KOMENTAZ
#WYŚWIETLANIE TEKSTU W KONSOLI
print("Hello, tu owca, wróciłam")

#TYP DANYCH -> STRING
owca = "owca jest fajna"
#TYP DANYCH -> LICZBY CALKOWITE (INT)
owcaJestLiczbaCalkowita = 7
#TYP DANYCH -> LICZBY ZMIENNOPRZECINKOWE(FLOAT)
owcaJestLiczbaZmiennoPrzecinkowa = 7.5
#TYP DANYCH -> PRWADA/FALSZ (BOOLEAN)
owcaPrawda = True
owcaFalsz = False
#SZYBKIE OPERACJE NA LICZBACH
#DZIELENIE MODULO CZYLI ZWRACANIE RESZTY Z DZIELENIA
print(7%5)#WYNIK TO 2
#POTENGOWANIE
print(2**5)#2 DO POTENGI 5
#PROBLEMY Z TYPAMI
print("7" , 7)
#FUNKCJA STR ZAMIENIA LICZBE NA NAPIS
print("7"+ str(7))
#TAKI FAJNY FUTURE ALE NIEWIEM JAK SIE NAZYWA
owcaFajn = 1234
print(f"Owca ma {1234} lat")